# .github/workflows/test-login.yml
name: Test Kibana Login

on:
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - 'login_test.py'

jobs:
  test-login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright pandas
        
    - name: Install Playwright browsers
      run: |
        playwright install chromium
        
    - name: Run login test
      env:
        KIBANA_BASE_URL: ${{ secrets.KIBANA_BASE_URL }}
        KIBANA_USERNAME: ${{ secrets.KIBANA_USERNAME }}
        KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
      run: python login_test.py
      
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: login-test-results
        path: |
          *.png
          *.html
        retention-days: 7
        
    - name: Test results summary
      if: always()
      run: |
        echo "Login test completed."
        echo "Check the artifacts for detailed screenshots and HTML files."
        echo "Files generated:"
        ls -la *.png *.html 2>/dev/null || echo "No debug files found"
